FROM python:3.7
EXPOSE 8501:8501
WORKDIR /app
COPY requirements.txt ./requirements.txt
RUN apt-get update && apt-get install -y python3-opencv
RUN pip install opencv-python
RUN pip3 install -r requirements.txt
COPY . .
CMD streamlit run app.py